version: 2.1
  jobs:
    build:
      docker: 
        - image: circleci/node:10.16.3
      steps:
        - checkout
        - run: npm build
        # - run: npm updateExampleHTMLs
        - run: npm test
